### ISSUE TITLE
Example throws UnhandledPromiseRejectionWarning: Error

### ISSUE THREAD

**Issue by Xeonzinc** [geekuillaume/node-audioworklet#2]
The example provided on the readme to create white noise (without separate .js file) produces the following error when I attempt to run it on its own. It seems to be related to the "const outputStream = device.openOutputStream({" statement, but my promises /ES6 knowledge is lacking so I'm struggling to diagnose further:

```
(node:15280) UnhandledPromiseRejectionWarning: Error: Unknown failure
    at C:\Users\emina\OneDrive\Room\Subsystems\Host\node_server\speaker_test.js:19:31
(node:15280) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:15280) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by geekuillaume** [comment]
Can you try again with the last version? I migrated from libsoudio to cubeb because libsoudio was not maintained anymore and cause some problems like this. There is some API changes with this migration but nothing too big.

**Comment by Xeonzinc** [comment]
I no longer receive the error, but no output occurs, it seems to stop the code at "getDefaultOutputDevice()"without outputting any error. A Console.log before this statement prints, console log after does not. 

The same occurs when trying to run the initial example to print all devices (when soundio is replaced with audioworker - the references in the example still refer to your old version)

**Comment by geekuillaume** [comment]
@Xeonzinc I cannot reproduce but you're not the only one with this problem. I've added a method to enable debug logs `AudioServer.setDebugLog(true);`. Can you try the `tests/debug_log.js` file?

**Comment by geekuillaume** [comment]
I've just fixed an error that would match your problem (thanks to @ThisIsAreku). Can you try again?

**Comment by Xeonzinc** [comment]
Hi geekuillaume, that seems to have sorted it. The white noise example now works as expected :) I'll keep playing with it and let you know if anything else crops up!

Also your soundsync project sounds great, its always annoyed me that there is no good way to output and sync to multiple devices easily. I used to use airfoil which kinda worked, but your solution seems much more comprehensive. I hope it is a success for you!

**Comment by geekuillaume** [comment]
Awesome, thanks :)
