### ISSUE TITLE
Segmentation fault: 11

### ISSUE THREAD

**Issue by LamboCreeper** [geekuillaume/node-audioworklet#6]
I'm trying to run the recording test that you have written (I changed the `../` to `audioworklet`), but all that happens is my console states `Segmentation fault: 11`. I'm not entirely sure how to troubleshoot this?

I am running macOS 10.14.6 and Node 12.13.0.

Any help would be greatly appreciated. 🙂

**Comment by geekuillaume** [comment]
Can you try with the latest version of this module? I've upgraded to the last libsoundio version and this fixes this crash in my tests

**Comment by LamboCreeper** [comment]
Yep, seems to be fixed. Thanks!
